
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.Table table4;
	
	private global::Gtk.CheckButton checkbuttonCSV;
	
	private global::Gtk.FileChooserButton fileChooserA;
	
	private global::Gtk.FileChooserButton fileChooserC;
	
	private global::Gtk.Label label18;
	
	private global::Gtk.Label label19;
	
	private global::Gtk.HBox hbox31;
	
	private global::Gtk.VBox vbox5;
	
	private global::Gtk.Label label22;
	
	private global::Gtk.Label label23;
	
	private global::Gtk.Label label24;
	
	private global::Gtk.Table table3;
	
	private global::Gtk.SpinButton buttonIterD;
	
	private global::Gtk.SpinButton buttonIterG;
	
	private global::Gtk.SpinButton buttonIterSA;
	
	private global::Gtk.SpinButton buttonMagicG;
	
	private global::Gtk.SpinButton buttonMutaG;
	
	private global::Gtk.SpinButton buttonPopG;
	
	private global::Gtk.SpinButton buttonReasonSA;
	
	private global::Gtk.Button buttonStartD;
	
	private global::Gtk.Button buttonStartG;
	
	private global::Gtk.Button buttonStartSA;
	
	private global::Gtk.SpinButton buttonTempSA;
	
	private global::Gtk.Label iterD;
	
	private global::Gtk.Label iterG;
	
	private global::Gtk.Label iterSA;
	
	private global::Gtk.Label label13;
	
	private global::Gtk.Label label14;
	
	private global::Gtk.Label label15;
	
	private global::Gtk.Label label16;
	
	private global::Gtk.Label label17;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TextView textOutput;
	
	private global::Gtk.ProgressBar progressBar;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(3));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.table4 = new global::Gtk.Table (((uint)(2)), ((uint)(3)), false);
		this.table4.Name = "table4";
		this.table4.RowSpacing = ((uint)(6));
		this.table4.ColumnSpacing = ((uint)(6));
		// Container child table4.Gtk.Table+TableChild
		this.checkbuttonCSV = new global::Gtk.CheckButton ();
		this.checkbuttonCSV.CanFocus = true;
		this.checkbuttonCSV.Name = "checkbuttonCSV";
		this.checkbuttonCSV.Label = global::Mono.Unix.Catalog.GetString ("Write Output to CSV File");
		this.checkbuttonCSV.Active = true;
		this.checkbuttonCSV.DrawIndicator = true;
		this.checkbuttonCSV.UseUnderline = true;
		this.table4.Add (this.checkbuttonCSV);
		global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table4 [this.checkbuttonCSV]));
		w1.LeftAttach = ((uint)(2));
		w1.RightAttach = ((uint)(3));
		w1.XOptions = ((global::Gtk.AttachOptions)(4));
		w1.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.fileChooserA = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select a File"), ((global::Gtk.FileChooserAction)(0)));
		this.fileChooserA.Name = "fileChooserA";
		this.table4.Add (this.fileChooserA);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table4 [this.fileChooserA]));
		w2.TopAttach = ((uint)(1));
		w2.BottomAttach = ((uint)(2));
		w2.LeftAttach = ((uint)(1));
		w2.RightAttach = ((uint)(2));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.fileChooserC = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select a File"), ((global::Gtk.FileChooserAction)(0)));
		this.fileChooserC.Name = "fileChooserC";
		this.table4.Add (this.fileChooserC);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table4 [this.fileChooserC]));
		w3.LeftAttach = ((uint)(1));
		w3.RightAttach = ((uint)(2));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.label18 = new global::Gtk.Label ();
		this.label18.Name = "label18";
		this.label18.Xalign = 0F;
		this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("Centers Input File");
		this.table4.Add (this.label18);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table4 [this.label18]));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.label19 = new global::Gtk.Label ();
		this.label19.Name = "label19";
		this.label19.Xalign = 0F;
		this.label19.LabelProp = global::Mono.Unix.Catalog.GetString ("Agencies Input File");
		this.table4.Add (this.label19);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table4 [this.label19]));
		w5.TopAttach = ((uint)(1));
		w5.BottomAttach = ((uint)(2));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox1.Add (this.table4);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table4]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox31 = new global::Gtk.HBox ();
		this.hbox31.Name = "hbox31";
		this.hbox31.Spacing = 6;
		// Container child hbox31.Gtk.Box+BoxChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.label22 = new global::Gtk.Label ();
		this.label22.Name = "label22";
		this.label22.Xalign = 0F;
		this.label22.LabelProp = global::Mono.Unix.Catalog.GetString ("Descent");
		this.vbox5.Add (this.label22);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.label22]));
		w7.Position = 0;
		w7.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.label23 = new global::Gtk.Label ();
		this.label23.Name = "label23";
		this.label23.Xalign = 0F;
		this.label23.LabelProp = global::Mono.Unix.Catalog.GetString ("Simulated Annealing");
		this.vbox5.Add (this.label23);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.label23]));
		w8.Position = 1;
		w8.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.label24 = new global::Gtk.Label ();
		this.label24.Name = "label24";
		this.label24.Xalign = 0F;
		this.label24.LabelProp = global::Mono.Unix.Catalog.GetString ("Genetic");
		this.vbox5.Add (this.label24);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.label24]));
		w9.Position = 2;
		w9.Fill = false;
		this.hbox31.Add (this.vbox5);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox31 [this.vbox5]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child hbox31.Gtk.Box+BoxChild
		this.table3 = new global::Gtk.Table (((uint)(3)), ((uint)(9)), false);
		this.table3.Name = "table3";
		this.table3.RowSpacing = ((uint)(6));
		this.table3.ColumnSpacing = ((uint)(6));
		// Container child table3.Gtk.Table+TableChild
		this.buttonIterD = new global::Gtk.SpinButton (1, 100000, 100);
		this.buttonIterD.CanFocus = true;
		this.buttonIterD.Name = "buttonIterD";
		this.buttonIterD.Adjustment.PageIncrement = 1;
		this.buttonIterD.ClimbRate = 1;
		this.buttonIterD.Numeric = true;
		this.buttonIterD.Value = 10000;
		this.table3.Add (this.buttonIterD);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonIterD]));
		w11.LeftAttach = ((uint)(1));
		w11.RightAttach = ((uint)(2));
		w11.XOptions = ((global::Gtk.AttachOptions)(4));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.buttonIterG = new global::Gtk.SpinButton (1, 100000, 100);
		this.buttonIterG.CanFocus = true;
		this.buttonIterG.Name = "buttonIterG";
		this.buttonIterG.Adjustment.PageIncrement = 1;
		this.buttonIterG.ClimbRate = 1;
		this.buttonIterG.Numeric = true;
		this.buttonIterG.Value = 10000;
		this.table3.Add (this.buttonIterG);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonIterG]));
		w12.TopAttach = ((uint)(2));
		w12.BottomAttach = ((uint)(3));
		w12.LeftAttach = ((uint)(1));
		w12.RightAttach = ((uint)(2));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.buttonIterSA = new global::Gtk.SpinButton (1, 100000, 100);
		this.buttonIterSA.CanFocus = true;
		this.buttonIterSA.Name = "buttonIterSA";
		this.buttonIterSA.Adjustment.PageIncrement = 1;
		this.buttonIterSA.ClimbRate = 1;
		this.buttonIterSA.Numeric = true;
		this.buttonIterSA.Value = 10000;
		this.table3.Add (this.buttonIterSA);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonIterSA]));
		w13.TopAttach = ((uint)(1));
		w13.BottomAttach = ((uint)(2));
		w13.LeftAttach = ((uint)(1));
		w13.RightAttach = ((uint)(2));
		w13.XOptions = ((global::Gtk.AttachOptions)(4));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.buttonMagicG = new global::Gtk.SpinButton (0, 1, 0.01);
		this.buttonMagicG.CanFocus = true;
		this.buttonMagicG.Name = "buttonMagicG";
		this.buttonMagicG.Adjustment.PageIncrement = 10;
		this.buttonMagicG.ClimbRate = 1;
		this.buttonMagicG.Digits = ((uint)(3));
		this.buttonMagicG.Numeric = true;
		this.buttonMagicG.Value = 0.01;
		this.table3.Add (this.buttonMagicG);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonMagicG]));
		w14.TopAttach = ((uint)(2));
		w14.BottomAttach = ((uint)(3));
		w14.LeftAttach = ((uint)(7));
		w14.RightAttach = ((uint)(8));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.buttonMutaG = new global::Gtk.SpinButton (0, 1, 0.01);
		this.buttonMutaG.CanFocus = true;
		this.buttonMutaG.Name = "buttonMutaG";
		this.buttonMutaG.Adjustment.PageIncrement = 10;
		this.buttonMutaG.ClimbRate = 1;
		this.buttonMutaG.Digits = ((uint)(3));
		this.buttonMutaG.Numeric = true;
		this.buttonMutaG.Value = 0.001;
		this.table3.Add (this.buttonMutaG);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonMutaG]));
		w15.TopAttach = ((uint)(2));
		w15.BottomAttach = ((uint)(3));
		w15.LeftAttach = ((uint)(5));
		w15.RightAttach = ((uint)(6));
		w15.XOptions = ((global::Gtk.AttachOptions)(4));
		w15.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.buttonPopG = new global::Gtk.SpinButton (1, 10000, 1);
		this.buttonPopG.CanFocus = true;
		this.buttonPopG.Name = "buttonPopG";
		this.buttonPopG.Adjustment.PageIncrement = 1;
		this.buttonPopG.ClimbRate = 1;
		this.buttonPopG.Numeric = true;
		this.buttonPopG.Value = 20;
		this.table3.Add (this.buttonPopG);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonPopG]));
		w16.TopAttach = ((uint)(2));
		w16.BottomAttach = ((uint)(3));
		w16.LeftAttach = ((uint)(3));
		w16.RightAttach = ((uint)(4));
		w16.XOptions = ((global::Gtk.AttachOptions)(4));
		w16.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.buttonReasonSA = new global::Gtk.SpinButton (0, 1, 0.01);
		this.buttonReasonSA.CanFocus = true;
		this.buttonReasonSA.Name = "buttonReasonSA";
		this.buttonReasonSA.Adjustment.PageIncrement = 0.01;
		this.buttonReasonSA.ClimbRate = 1;
		this.buttonReasonSA.Digits = ((uint)(3));
		this.buttonReasonSA.Numeric = true;
		this.buttonReasonSA.Value = 0.3;
		this.table3.Add (this.buttonReasonSA);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonReasonSA]));
		w17.TopAttach = ((uint)(1));
		w17.BottomAttach = ((uint)(2));
		w17.LeftAttach = ((uint)(3));
		w17.RightAttach = ((uint)(4));
		w17.XOptions = ((global::Gtk.AttachOptions)(4));
		w17.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.buttonStartD = new global::Gtk.Button ();
		this.buttonStartD.CanFocus = true;
		this.buttonStartD.Name = "buttonStartD";
		this.buttonStartD.UseUnderline = true;
		this.buttonStartD.Label = global::Mono.Unix.Catalog.GetString ("Start");
		this.table3.Add (this.buttonStartD);
		global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonStartD]));
		w18.LeftAttach = ((uint)(8));
		w18.RightAttach = ((uint)(9));
		w18.XOptions = ((global::Gtk.AttachOptions)(4));
		w18.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.buttonStartG = new global::Gtk.Button ();
		this.buttonStartG.CanFocus = true;
		this.buttonStartG.Name = "buttonStartG";
		this.buttonStartG.UseUnderline = true;
		this.buttonStartG.Label = global::Mono.Unix.Catalog.GetString ("Start");
		this.table3.Add (this.buttonStartG);
		global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonStartG]));
		w19.TopAttach = ((uint)(2));
		w19.BottomAttach = ((uint)(3));
		w19.LeftAttach = ((uint)(8));
		w19.RightAttach = ((uint)(9));
		w19.XOptions = ((global::Gtk.AttachOptions)(4));
		w19.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.buttonStartSA = new global::Gtk.Button ();
		this.buttonStartSA.CanFocus = true;
		this.buttonStartSA.Name = "buttonStartSA";
		this.buttonStartSA.UseUnderline = true;
		this.buttonStartSA.Label = global::Mono.Unix.Catalog.GetString ("Start");
		this.table3.Add (this.buttonStartSA);
		global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonStartSA]));
		w20.TopAttach = ((uint)(1));
		w20.BottomAttach = ((uint)(2));
		w20.LeftAttach = ((uint)(8));
		w20.RightAttach = ((uint)(9));
		w20.XOptions = ((global::Gtk.AttachOptions)(4));
		w20.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.buttonTempSA = new global::Gtk.SpinButton (0, 10000, 10);
		this.buttonTempSA.CanFocus = true;
		this.buttonTempSA.Name = "buttonTempSA";
		this.buttonTempSA.Adjustment.PageIncrement = 10;
		this.buttonTempSA.ClimbRate = 1;
		this.buttonTempSA.Numeric = true;
		this.buttonTempSA.Value = 700;
		this.table3.Add (this.buttonTempSA);
		global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table3 [this.buttonTempSA]));
		w21.TopAttach = ((uint)(1));
		w21.BottomAttach = ((uint)(2));
		w21.LeftAttach = ((uint)(5));
		w21.RightAttach = ((uint)(6));
		w21.XOptions = ((global::Gtk.AttachOptions)(4));
		w21.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.iterD = new global::Gtk.Label ();
		this.iterD.Name = "iterD";
		this.iterD.Xalign = 0F;
		this.iterD.LabelProp = global::Mono.Unix.Catalog.GetString ("Iterations");
		this.table3.Add (this.iterD);
		global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table3 [this.iterD]));
		w22.XOptions = ((global::Gtk.AttachOptions)(4));
		w22.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.iterG = new global::Gtk.Label ();
		this.iterG.Name = "iterG";
		this.iterG.Xalign = 0F;
		this.iterG.LabelProp = global::Mono.Unix.Catalog.GetString ("Iterations");
		this.table3.Add (this.iterG);
		global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table3 [this.iterG]));
		w23.TopAttach = ((uint)(2));
		w23.BottomAttach = ((uint)(3));
		w23.XOptions = ((global::Gtk.AttachOptions)(4));
		w23.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.iterSA = new global::Gtk.Label ();
		this.iterSA.Name = "iterSA";
		this.iterSA.Xalign = 0F;
		this.iterSA.LabelProp = global::Mono.Unix.Catalog.GetString ("Iterations");
		this.table3.Add (this.iterSA);
		global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table3 [this.iterSA]));
		w24.TopAttach = ((uint)(1));
		w24.BottomAttach = ((uint)(2));
		w24.XOptions = ((global::Gtk.AttachOptions)(4));
		w24.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.label13 = new global::Gtk.Label ();
		this.label13.Name = "label13";
		this.label13.Xalign = 0F;
		this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Geometric Reason");
		this.table3.Add (this.label13);
		global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table3 [this.label13]));
		w25.TopAttach = ((uint)(1));
		w25.BottomAttach = ((uint)(2));
		w25.LeftAttach = ((uint)(2));
		w25.RightAttach = ((uint)(3));
		w25.XOptions = ((global::Gtk.AttachOptions)(4));
		w25.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.label14 = new global::Gtk.Label ();
		this.label14.Name = "label14";
		this.label14.Xalign = 0F;
		this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Population");
		this.table3.Add (this.label14);
		global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table3 [this.label14]));
		w26.TopAttach = ((uint)(2));
		w26.BottomAttach = ((uint)(3));
		w26.LeftAttach = ((uint)(2));
		w26.RightAttach = ((uint)(3));
		w26.XOptions = ((global::Gtk.AttachOptions)(4));
		w26.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.label15 = new global::Gtk.Label ();
		this.label15.Name = "label15";
		this.label15.Xalign = 0F;
		this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("Init Temperature");
		this.table3.Add (this.label15);
		global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table3 [this.label15]));
		w27.TopAttach = ((uint)(1));
		w27.BottomAttach = ((uint)(2));
		w27.LeftAttach = ((uint)(4));
		w27.RightAttach = ((uint)(5));
		w27.XOptions = ((global::Gtk.AttachOptions)(4));
		w27.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.label16 = new global::Gtk.Label ();
		this.label16.Name = "label16";
		this.label16.Xalign = 0F;
		this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("Mutation Probability");
		this.table3.Add (this.label16);
		global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table3 [this.label16]));
		w28.TopAttach = ((uint)(2));
		w28.BottomAttach = ((uint)(3));
		w28.LeftAttach = ((uint)(4));
		w28.RightAttach = ((uint)(5));
		w28.XOptions = ((global::Gtk.AttachOptions)(4));
		w28.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.label17 = new global::Gtk.Label ();
		this.label17.Name = "label17";
		this.label17.Xalign = 0F;
		this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("Magic Probability");
		this.table3.Add (this.label17);
		global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table3 [this.label17]));
		w29.TopAttach = ((uint)(2));
		w29.BottomAttach = ((uint)(3));
		w29.LeftAttach = ((uint)(6));
		w29.RightAttach = ((uint)(7));
		w29.XOptions = ((global::Gtk.AttachOptions)(4));
		w29.YOptions = ((global::Gtk.AttachOptions)(4));
		this.hbox31.Add (this.table3);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox31 [this.table3]));
		w30.PackType = ((global::Gtk.PackType)(1));
		w30.Position = 1;
		w30.Expand = false;
		w30.Fill = false;
		this.vbox1.Add (this.hbox31);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox31]));
		w31.Position = 1;
		w31.Expand = false;
		w31.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textOutput = new global::Gtk.TextView ();
		this.textOutput.Buffer.Text = "Please choose a file, then setup your parameters and start an algorithm.\n\n";
		this.textOutput.CanFocus = true;
		this.textOutput.Name = "textOutput";
		this.textOutput.CursorVisible = false;
		this.GtkScrolledWindow.Add (this.textOutput);
		this.vbox1.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
		w33.Position = 2;
		// Container child vbox1.Gtk.Box+BoxChild
		this.progressBar = new global::Gtk.ProgressBar ();
		this.progressBar.Name = "progressBar";
		this.vbox1.Add (this.progressBar);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.progressBar]));
		w34.Position = 3;
		w34.Expand = false;
		w34.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 954;
		this.DefaultHeight = 549;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.fileChooserC.SelectionChanged += new global::System.EventHandler (this.OnFileChooserCSelectionChanged);
		this.fileChooserA.SelectionChanged += new global::System.EventHandler (this.OnFileChooserASelectionChanged);
		this.checkbuttonCSV.Toggled += new global::System.EventHandler (this.OnCheckbuttonCSVToggled);
		this.buttonStartSA.Clicked += new global::System.EventHandler (this.OnButtonStartSAClicked);
		this.buttonStartG.Clicked += new global::System.EventHandler (this.OnButtonStartGClicked);
		this.buttonStartD.Clicked += new global::System.EventHandler (this.OnButtonStartDClicked);
	}
}
